import { DBMS } from '../data/dbTypes';

export function generateDDL(tables, relationships, dbms) {
  const q = getQuoteChar(dbms);
  const lines = [];

  lines.push(`-- Generated by DrawDB Free`);
  lines.push(`-- DBMS: ${dbms}`);
  lines.push(`-- Date: ${new Date().toISOString()}`);
  lines.push('');

  // CREATE TABLE statements
  for (const table of tables) {
    lines.push(generateCreateTable(table, dbms, q));
    lines.push('');
  }

  // ALTER TABLE for foreign keys
  for (const rel of relationships) {
    const fromTable = tables.find(t => t.id === rel.fromTable);
    const toTable = tables.find(t => t.id === rel.toTable);
    if (!fromTable || !toTable) continue;

    const fromCol = fromTable.columns.find(c => c.id === rel.fromColumn);
    const toCol = toTable.columns.find(c => c.id === rel.toColumn);
    if (!fromCol || !toCol) continue;

    const constraintName = `${fromTable.name}_${fromCol.name}_foreign`;
    lines.push(`ALTER TABLE ${q}${fromTable.name}${q} ADD CONSTRAINT ${q}${constraintName}${q} FOREIGN KEY (${q}${fromCol.name}${q}) REFERENCES ${q}${toTable.name}${q} (${q}${toCol.name}${q});`);
  }

  return lines.join('\n');
}

function generateCreateTable(table, dbms, q) {
  const lines = [];
  lines.push(`CREATE TABLE ${q}${table.name}${q} (`);

  const colDefs = [];
  const pkCols = [];

  for (const col of table.columns) {
    let def = `  ${q}${col.name}${q} `;

    // Type
    if (dbms === DBMS.POSTGRESQL && col.autoIncrement) {
      if (col.type === 'BIGINT' || col.type === 'BIGSERIAL') def += 'BIGSERIAL';
      else if (col.type === 'SMALLINT' || col.type === 'SMALLSERIAL') def += 'SMALLSERIAL';
      else def += 'SERIAL';
    } else if (dbms === DBMS.SQLSERVER && col.type === 'NVARCHAR' && col.length === 'MAX') {
      def += 'NVARCHAR(MAX)';
    } else {
      def += col.type;
      if (col.type === 'ENUM' || col.type === 'SET') {
        if (col.enumValues) {
          const vals = col.enumValues.split(',').map(v => `'${v.trim()}'`).join(', ');
          def += `(${vals})`;
        }
      } else if (col.length) {
        def += `(${col.length})`;
      }
      if (col.isArray && dbms === DBMS.POSTGRESQL) {
        def += '[]';
      }
    }

    // Unsigned (MySQL)
    if (col.unsigned && dbms === DBMS.MYSQL) {
      def += ' UNSIGNED';
    }

    // Auto increment
    if (col.autoIncrement && dbms === DBMS.MYSQL) {
      def += ' AUTO_INCREMENT';
    } else if (col.autoIncrement && dbms === DBMS.SQLSERVER) {
      def += ' IDENTITY(1,1)';
    }

    // NOT NULL
    if (!col.nullable) {
      def += ' NOT NULL';
    } else {
      def += ' NULL';
    }

    // UNIQUE
    if (col.unique && !col.primaryKey) {
      def += ' UNIQUE';
    }

    // DEFAULT
    if (col.default !== undefined && col.default !== '') {
      const defaultVal = formatDefault(col.default, col.type, dbms);
      def += ` DEFAULT ${defaultVal}`;
    }

    // COMMENT (MySQL)
    if (col.comment && dbms === DBMS.MYSQL) {
      def += ` COMMENT '${col.comment.replace(/'/g, "''")}'`;
    }

    if (col.primaryKey) pkCols.push(col.name);
    colDefs.push(def);
  }

  // Primary key constraint
  if (pkCols.length > 0) {
    colDefs.push(`  PRIMARY KEY (${pkCols.map(c => `${q}${c}${q}`).join(', ')})`);
  }

  // Composite indexes
  for (const idx of table.indexes) {
    const idxColNames = idx.columns
      .map(cId => table.columns.find(c => c.id === cId)?.name)
      .filter(Boolean);

    if (idxColNames.length === 0) continue;

    if (idx.type === 'UNIQUE') {
      colDefs.push(`  UNIQUE (${idxColNames.map(c => `${q}${c}${q}`).join(', ')})`);
    }
  }

  lines.push(colDefs.join(',\n'));
  lines.push(');');

  // Table comment (PostgreSQL / SQL Server)
  if (table.comment) {
    if (dbms === DBMS.POSTGRESQL) {
      lines.push(`COMMENT ON TABLE ${q}${table.name}${q} IS '${table.comment.replace(/'/g, "''")}';`);
    } else if (dbms === DBMS.MYSQL) {
      // MySQL table comment is in CREATE TABLE
      lines[lines.length - 1] = lines[lines.length - 1].replace(');', `) COMMENT='${table.comment.replace(/'/g, "''")}';`);
    }
  }

  // Column comments (PostgreSQL)
  if (dbms === DBMS.POSTGRESQL) {
    for (const col of table.columns) {
      if (col.comment) {
        lines.push(`COMMENT ON COLUMN ${q}${table.name}${q}.${q}${col.name}${q} IS '${col.comment.replace(/'/g, "''")}';`);
      }
    }
  }

  // Non-unique indexes as separate CREATE INDEX
  for (const idx of table.indexes) {
    if (idx.type === 'INDEX') {
      const idxColNames = idx.columns
        .map(cId => table.columns.find(c => c.id === cId)?.name)
        .filter(Boolean);
      if (idxColNames.length === 0) continue;
      const idxName = idx.name || `idx_${table.name}_${idxColNames.join('_')}`;
      lines.push(`CREATE INDEX ${q}${idxName}${q} ON ${q}${table.name}${q} (${idxColNames.map(c => `${q}${c}${q}`).join(', ')});`);
    }
  }

  return lines.join('\n');
}

function formatDefault(value, type, dbms) {
  // Check if it's a SQL function
  const sqlFunctions = ['now()', 'current_timestamp', 'current_date', 'current_time',
    'uuid_generate_v4()', 'gen_random_uuid()', 'newid()', 'getdate()', 'getutcdate()',
    'sysdatetime()', 'null'];

  if (sqlFunctions.some(f => value.toLowerCase() === f)) {
    return value;
  }

  // Check if numeric
  if (/^-?\d+(\.\d+)?$/.test(value)) {
    return value;
  }

  // Check if boolean
  if (/^(true|false)$/i.test(value)) {
    if (dbms === DBMS.MYSQL) return value.toUpperCase() === 'TRUE' ? '1' : '0';
    return value.toUpperCase();
  }

  // String
  return `'${value.replace(/'/g, "''")}'`;
}

function getQuoteChar(dbms) {
  switch (dbms) {
    case DBMS.MYSQL: return '`';
    case DBMS.POSTGRESQL: return '"';
    case DBMS.SQLSERVER: return '"';
    default: return '`';
  }
}
